
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/user/cmake_3_30_6_version/cmake_3_30_6_build/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.4.0-198-generic - x86_64
...
